### ISSUE TITLE
If a statement does not end with a semicolon and ends with a closing tag, is the endFilePos attribute of this statement correct?

### ISSUE THREAD

**Issue by zhaoyanliang2** [nikic/PHP-Parser#600] opened 2019-04-16 14:56 UTC
```php
$code = <<<CODE
<?php echo something; test() ?>
<?php echo something;?>
CODE;

$lexer = new PhpParser\Lexer\Emulative(array('usedAttributes' => array(
	'startLine', 'endLine', 'startFilePos', 'endFilePos', 'comments'
)));
$parser = (new PhpParser\ParserFactory)->create(
	PhpParser\ParserFactory::PREFER_PHP7,
	$lexer
);
$stmts = $parser->parse($code);

foreach ( $stmts as $stmt ) {
	$startPos = $stmt->getAttribute('startFilePos');
	$endPos = $stmt->getAttribute('endFilePos');
	$length = $endPos - $startPos + 1;
	$stmtCode = substr($code, $startPos, $length);
	echo $stmtCode . PHP_EOL;
}
```
------------------------

**Output:**
echo something;
test() ?>

echo something;

------------------------

**Expected output:**
echo something;
test()
echo something;

------------------------

Is this a bug?

**Comment by nikic** [comment] 2019-04-16 15:23
Not a bug in itself, though I'm sure that the formatting-preserving pretty printer has bugs as a result of this. The problem is that `?>` in PHP acts as an implicit semicolon. `test()` by itself is not a legal statement, but `test() ?>` is, so it has to be part of the offsets of the statement node.

**Comment by hengyu654** [comment] 2019-04-16 15:59
I am trying to modify the code using the two attributes startFilePos and endFilePos to avoid reformatting the entire file. It works well except for the statement that ends with a closing tag. If I remove this statement from the code via the two attributes startFilePos and endFilePos, it will cause the closing tag to be missing.
Is there a simple way to know if a statement ends with a semicolon or with a closing tag? Do you consider adding a attribute to the Stmt class to implement it in the future?

**Comment by TomasVotruba** [comment] 2019-04-16 16:03
You don't need to work with positions to add/remove nodes.

What is you ultimate goal?
A diff would be the best

I use node modifications in @rectorphp extensively, so I might help

**Comment by nikic** [comment] 2019-04-16 16:08
@hengyu654 A simple way to check would be:

```
$tokens = $lexer->getTokens(); // Retrieved when parsing
if ($tokens[$node->getTokenEndPos()] == T_CLOSE_TAG) { ... }
```

**Comment by hengyu654** [comment] 2019-04-16 16:18
@TomasVotruba 
My ultimate goal is to modify the code without reformatting.

@nikic 
Thanks for your help.

**Comment by TomasVotruba** [comment] 2019-04-16 16:26
I see. I went that way first too, then more and more formatting troubles occured and I realized I'm creating another PHP_CodeSniffer. 

I decided to delegated the formatting to EasyCodingStandard and that allowed me to put more focus on modifications themselves

**Comment by hengyu654** [comment] 2019-04-16 17:31
@nikic 
> @hengyu654 A simple way to check would be:
> 
> ```
> $tokens = $lexer->getTokens(); // Retrieved when parsing
> if ($tokens[$node->getTokenEndPos()] == T_CLOSE_TAG) { ... }
> ```

It doesn't work, because the `$tokens`'s key is not the file postition.
I wrote the following:
```php
$stmtCode = substr($code, $startPos, $length);
if ( substr(rtrim($stmtCode), -2) === '?>' ) {
	//something todo
}
```
Seems unreliable but normally works

**Comment by nikic** [comment] 2019-04-16 17:36
> It doesn't work, because the $tokens's key is not the file postition.

True, but that's why I used `getTokenEndPos()` rather than `getFileEndPos()` there.

Your variant should work just as well though.

**Closed** 2019-08-08 14:55 UTC
