### ISSUE TITLE
PHP 8.1: PHP-Parser breaks on parameter passed by reference

### ISSUE THREAD

**Issue by ondrejmirtes** [nikic/PHP-Parser#794] opened 2021-07-08 13:28 UTC
With this code example:

```php
<?php

function foo(array &$one) {}
```

PHP-Parser (`/bin/php-parse`) crashes with:

```
====> File /app/vendor/nikic/php-parser/bin/test.php:

Warning: Undefined array key 402 in /app/vendor/nikic/php-parser/lib/PhpParser/Lexer.php on line 323

Fatal error: Uncaught TypeError: PhpParser\Lexer::getNextToken(): Return value must be of type int, null returned in /app/vendor/nikic/php-parser/lib/PhpParser/Lexer.php:364
Stack trace:
#0 /app/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php(209): PhpParser\Lexer->getNextToken('&', Array, Array)
#1 /app/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php(159): PhpParser\ParserAbstract->doParse()
#2 /app/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(51): PhpParser\ParserAbstract->parse('<?php\n\nfunction...', Object(PhpParser\ErrorHandler\Throwing))
#3 /app/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(32): PhpParser\Parser\Multiple->tryParse(Object(PhpParser\Parser\Php7), Object(PhpParser\ErrorHandler\Throwing), '<?php\n\nfunction...')
#4 /app/vendor/nikic/php-parser/bin/php-parse(71): PhpParser\Parser\Multiple->parse('<?php\n\nfunction...')
#5 {main}
  thrown in /app/vendor/nikic/php-parser/lib/PhpParser/Lexer.php on line 364
```

**Comment by nikic** [comment] 2021-07-08 13:46
This is an expected breakage caused by the introduction of intersection types. Will have to adjust for the two different `&` tokens.

**Comment by ondrejmirtes** [comment] 2021-07-08 13:48
Thanks!

**Comment by nikic** [comment] 2021-07-09 15:10
Should be fixed by https://github.com/nikic/PHP-Parser/commit/c758510a37218d631fd10f67bca5bccbfef864fa.

**Closed by nikic** 2021-07-09 15:10 UTC
