### ISSUE TITLE
Empty lines will get ignored

### ISSUE THREAD

**Issue by PhillippOhlandt** [nikic/PHP-Parser#305] opened 2016-09-23 19:41 UTC
Hey,

When I parse the following code

```
<?php

namespace Bolt\Extension\Ohlandt\Test;

use Bolt\Extension\SimpleExtension;

/**
 * Test extension class.
 *
 * @author Your Name <you@example.com>
 */
class TestExtension extends SimpleExtension
{

}
```

and then generate the PHP again, I get this output:

```
<?php

namespace Bolt\Extension\Ohlandt\Test;

use Bolt\Extension\SimpleExtension;
/**
 * Test extension class.
 *
 * @author Your Name <you@example.com>
 */
class TestExtension extends SimpleExtension
{
}
```

As you can see, the empty line above the docblock is gone. Weird thing is, when I `print_r` the parsed statements, I can see in the docblock node, that the line is set to 7 (`[line:protected] => 7`). But the generated PHP code has the docblock at line 6. 

Is this a bug or intended?

**Comment by nikic** [comment] 2016-09-23 21:05
The pretty printer does not preserve code formatting. In your case the difference is just those newlines, because your coding style happens to match what the pretty printer uses by default. (Though there are some things that probably should be changed, like leaving a blank line after `use` and between methods etc.)

**Comment by PhillippOhlandt** [comment] 2016-09-23 21:36
Yeah I get that the pretty printer doesn't preserve code formatting. But in this case, the information about the starting line for the docblock is there, it just won't get used. Any ideas for a workaround?

**Comment by nikic** [comment] 2016-09-23 21:42
As a workaround, you could try extending [pStmts](https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/PrettyPrinterAbstract.php#L181) by keeping track of the ending line of the previous statement and comparing that to the start line of the current statement (or the first comment on the current statement, if it has one) and adding the difference in extra newlines. That will probably give a pretty good approximation, though there's probably some edge cases.

**Comment by PhillippOhlandt** [comment] 2016-09-23 21:44
Ah, interesting. Will play a little bit with that. It's the first time I use this library and I want to use it mainly for inserting functions or function content into existing classes.

**Comment by nikic** [comment] 2017-01-18 23:00
Closing this as a duplicate of #41. Per the last comments on that issue, there has recently some movement towards proper support for preserving formatting, so there's hope this will be possible soon :)

**Closed by nikic** 2017-01-18 23:00 UTC
