### ISSUE TITLE
PHPDoc detection

### ISSUE THREAD

**Issue by ElisDN** [nikic/PHP-Parser#692] opened 2020-07-26 08:29 UTC
Property errors appear in Psalm after updating `nikic/php-parser` to 4.7.0:

https://github.com/vimeo/psalm/issues/3896

**Comment by muglug** [comment] 2020-07-26 13:43
This is a dupe of https://github.com/nikic/PHP-Parser/issues/690

**Comment by nikic** [comment] 2020-07-26 13:58
Why is this a duplicate of #690? The given code shouldn't be affected by PHP 8 differences.

**Comment by muglug** [comment] 2020-07-26 14:18
Ah, I just assumed something was up with PHP 8-related tokenisation. Either way, I don't think the bug belongs in this repo (it it indeed exists – the issue in that particular code is, I think, related to a Psalm config flag `usePhpDocPropertiesWithoutMagicCall` that is disabled by default but would make the code in question work.

**Closed** 2021-08-01 14:07 UTC
