### ISSUE TITLE
Remove node that are in one line

### ISSUE THREAD

**Issue by kl3sk** [nikic/PHP-Parser#909] opened 2022-12-23 09:42 UTC
Hello,

I want to remove node (Trait1 only in this example) if they are like this
```php
class MyClass {
     use Trait1, Trait2;
}
```

My node visitor in `leaveNode` return an array of `Node\Name`. 

```php
public function leaveNode(Node $node)
{
    if ($node instanceof Node\Stmt\TraitUse) {
        $node->traits; // list of trait
    }
}
```

With many tries, I only archived to have (for example):

`use , Trait2;` or even worst `use ;`

Thank for you help

**Comment by nikic** [comment] 2022-12-23 20:22
Could you share the actual code you're using in leaveNode()? Also, are you using the formatting-preserving pretty printer?

**Comment by kl3sk** [comment] 2023-01-02 09:13
Hello,

I didn't have the same behaviour, but I play around this:

```php
        if ($node instanceof Node\Stmt\TraitUse) {
            $searched = $this->getTrait();

            if ($this->getMode() === 'remove') {
                foreach ($node->traits as $index => $trait) {
                    if (\in_array($searched, $trait->parts)) {
                        unset($node->traits[$index]);
                        // return NodeTraverser::REMOVE_NODE;
                    }
                }
            } else {
                foreach ($node->traits as $trait) {
                    if (\in_array($searched, $trait->parts)) {
                        $this->canAdd = false;
                    }
                }
            }
        }
```

Independently, with `unset` or `NodeTraverser::REMOVE_NODE`
and
```php
use Trait1;
use Trait2;
```
or
```php
use Trait1, Trait2;
```

Doesn't result to the same result.

Finally, I use the `printFormatPreserving`, with `prettyPrintFile` it doesn't have the same behaviour. Especially with the `unset` method.

**Comment by nikic** [comment] 2023-03-05 20:08
I see. The problem is that the formatting-preserving printer assumes that arrays are lists (in the array_is_list sense), while `unset()` leaves behind a hole in the index sequence. This ends up completely breaking things (the `Differ` actually throws a notice).

It might make sense to handle this situation more gracefully.

**Comment by nikic** [comment] 2023-05-21 13:16
Fixed by https://github.com/nikic/PHP-Parser/commit/289756d0568bef538cd0114f131daef6a7d626d8.

**Closed by nikic** 2023-05-21 13:16 UTC
