### ISSUE TITLE
Comments on empty blocks are dropped.

### ISSUE THREAD

**Issue by tsufeki** [nikic/PHP-Parser#382] opened 2017-05-01 18:17 UTC
```
$ php-parse --var-dump '<?php /* a */{}'
====> Code <?php /* a */{}
==> var_dump():
/home/.../bin/php-parse:86:
array(0) {
}
```
Non-empty blocks work fine. I'm using master.

**Comment by tsufeki** [comment] 2017-05-01 19:23
It seems that comments "in the middle" of compound statements are ignored too, for example
```php
<?php if /* a */ (7) {}
```

**Comment by tsufeki** [comment] 2017-05-01 20:07
One more thing: comments are often repeated, i.e. same comment appears in many nodes. This can be seen in tests, for example [parser/blockComments.test](https://github.com/nikic/PHP-Parser/blob/master/test/code/parser/blockComments.test). Is this intended? If so, what are the rules for repetition? Thanks for your work.

**Comment by limeblack** [comment] 2017-07-24 19:52
@tsufeki in my opinion `<?php if /* a */ (7) {}` is acted as intended.  I believe the comments are intended for typical documentation which wouldn't include such.

**Comment by nikic** [comment] 2017-10-01 15:19
There are three separate issues here:

 * Preservation of comments on empty blocks. This has been fixed by https://github.com/nikic/PHP-Parser/commit/d418bf395113b6a3293bda1d08ddc9b0209d5dcf.
 * Duplicate comments. This is a known bug tracked in #253.
 * Comments in the middle of nodes. These are indeed not represented. As usual, it's possible to extract them using token offsets and a bit of extra work. Assuming token offsets are enabled in the lexer, something along the lines of (not tested):

```php
// $tokens from Lexer->getTokens()
function getInteriorComments(Node $node, array $tokens) {
    $comments = [];
    $pos = $node->getStartTokenPos();
    foreach ($node->getSubNodeNames() as $name) {
        $subNode = $node->$name;
        if ($subNode instanceof Node) {
            $endPos = backwardsAdjust($tokens, $subNode->getStartTokenPos());
            $comments = array_merge($comments, extractComments($tokens, $pos, $endPos));
            $pos = $subNode->getEndTokenPos() + 1;
        }
    }
    $endPos = $node->getEndTokenPos() + 1;
    $comments = array_merge($comments, extractComments($tokens, $pos, $endPos));
    return $comments;
}

function extractComments(array $tokens, int $startPos, int $endPos) {
    $comments = [];
    for ($pos = $startPos; $pos < $endPos; $pos++) {
        $token = $tokens[$pos];
        if ($token[0] === T_COMMENT) {
            $comments[] = new Comment($token[1]);
        } else if ($token[0] === T_DOC_COMMENT) {
            $comments[] = new Comment\Doc($token[1]);
        }
    }
    return $comments;
}

function backwardsAdjust(array $tokens, int $pos) {
    for (; $pos > 0; $pos--) {
        $token = $tokens[$pos-1];
        if (!in_array($token[0], [T_COMMENT, T_DOC_COMMENT, T_WHITESPACE])) {
            break;
        }
    }
    return $pos;
}
```

What this code does is to fetch all the comments that are inside the node but not inside a subnode. An additional complication (the backwardsAdjust function) is that we also want to skip the comments that are directly preceding the subnodes, as there will already be associated with the subnodes. (This would have been somewhat easier if comments also stored their starting token offset -- they currently only have the file offset.)

**Closed by nikic** 2017-10-01 15:19 UTC
