### ISSUE TITLE
Keywords reserved and AST not built

### ISSUE THREAD

**Issue by llaville** [nikic/PHP-Parser#202] opened 2015-05-26 09:15 UTC
Hello Nikita,

I've found an issue on build AST process with keywords reserved.
Let me explains with an example: 
 `trait` keyword is reserved since PHP 5.4 and a token T_TRAIT exists

If you try to analyse such source code, with PHP 5.3
```php
<?php

class trait
{
}
```
You should NOT get any error with PHP-Parser, because trait is declared as a T_STRING token

Here are the list I get
```
(
    [0] => Array
        (
            [0] => 368
            [1] => <?php

            [2] => 1
        )

    [1] => Array
        (
            [0] => 371
            [1] =>

            [2] => 2
        )

    [2] => Array
        (
            [0] => 353
            [1] => class
            [2] => 3
        )

    [3] => Array
        (
            [0] => 371
            [1] =>
            [2] => 3
        )

    [4] => Array
        (
            [0] => 307
            [1] => trait
            [2] => 3
        )

    [5] => Array
        (
            [0] => 371
            [1] =>

            [2] => 3
        )

    [6] => {
    [7] => Array
        (
            [0] => 371
            [1] =>

            [2] => 4
        )

    [8] => }
    [9] => Array
        (
            [0] => 371
            [1] =>

            [2] => 5
        )

)
```
And  token_name(307), gave me T_STRING with PHP 5.3.29

But, if I run this script (still with PHP 5.3.29) with PHP-Parser 1.3.0
```php
<?php

require_once dirname(__DIR__) . '/vendor/autoload.php';

use PhpParser\Node;

$lexer      = new PhpParser\Lexer\Emulative;
$parser     = new PhpParser\Parser($lexer);
$traverser  = new PhpParser\NodeTraverser;
$traverser->addVisitor(new PhpParser\NodeVisitor\NameResolver);

$code = '<?php

class trait
{
}
';

try {
    $stmts  = $parser->parse($code);
    $tokens = $lexer->getTokens();
    
    $stmts = $traverser->traverse($stmts); 
    echo 'all statements', PHP_EOL;
    print_r( $stmts );    
    print_r( $tokens );    
        
        
} catch (PhpParser\Error $e) {
    echo 'Parse Error: ', $e->getMessage();
}
```
 I have such results : 
```
Parse Error: Syntax error, unexpected T_TRAIT, expecting T_STRING on line 3
```

This is difficult to have a NodeVisitor that search for keywords reserved in such condition.
Did you've a solution to suggest ?

Thanks in advance.
Laurent

**Comment by nikic** [comment] 2015-05-26 14:07
This happens because you're using `PhpParser\Lexer\Emulative`, which will try to tokenize the code as if you were running on a more recent PHP version. If you use `PhpParser\Lexer` the token_get_all output will be used directly and you should be able to parse the posted source code.

**Comment by llaville** [comment] 2015-05-26 14:41
Ok, so If I've well understood, with same code (without emulative lexer), we CAN both parsed old code valid for PHP 5.3 and new code PHP 5.4 , 5.5 or 5.6.
Or is it something I 've forgotten, or misunderstood with the emulative lexer.

**Comment by llaville** [comment] 2015-05-26 14:42
In doc we can read 

> Use of the emulative lexer is required if you want to parse PHP code from newer versions than the one you're running on. For example it will allow you to parse PHP 5.6 code while running on PHP 5.3.

**Comment by nikic** [comment] 2015-05-26 14:56
Yes, if you want to parse newer PHP versions, the emulative lexer is required - in which case you also cannot use the new keywords as identifiers. I don't think I can really do anything about that.

If you want to detect whether new keywords are used, maybe just scan token_get_all output for it?

**Comment by llaville** [comment] 2015-05-26 15:19
My goal is to write an analyser (for php-compatinfo) that is supposed to scan source code and checks old elements found to migrate easily from an old PHP version to a new one.

Actually I know three projects that try to did it : 

- https://github.com/wimg/PHPCompatibility/ , but it's only for PHP_CodeSniffer that used only tokenizer extension
- https://github.com/monque/PHP-Migration, that used PHP-Parser, but i'ts certainly impossible to do it (used also the lexer emulataive)
- https://github.com/suralc/pvra, that used PHP-Parser and and extended version of your lexer emulative.

My project (php-compatinfo) is able to accept 1 to many analysers (NodeVisitor) at same time, but always used the same php-parser run-time.

So I don't think (now) we can have a simple solution. 

Such migration analyser is probably a good idea, and its most popular in PHPCompatibilty project (by wimg). I'd really like a such alternative with AST and PHP-Parser.

If someone has an idea, feel free to share !

**Comment by llaville** [comment] 2015-05-27 17:09
@nikic Good news. I've found a solution that will allow to detect keyword reserved with the emulative lexer and keep it working as expected.

As the fix must be applied on the lexer emulative, I'll propose you a diff that I'll explains now !

We can either use a new option to configure it, but for now, I've only set the keywords reserved detection to class (T_CLASS) and function (T_FUNCTION) context. See the `$allowKeywordsReserved` property.

If we run a build AST script (as declared in my introduction) with PHP 5.3, only new keywords (with PHP 5.4, 5.5, see `$newKeywords` property) will be accepted in class and function name context. 
The token won't be replaced and keep it as T_STRING
Otherwise the token T_STRING will be replaced by its new value configured (`$newKeywords`).

What do you think of this proposition ?

```
diff --git a/lib/PhpParser/Lexer/Emulative.php b/lib/PhpParser/Lexer/Emulative.php
index 837def4..4656064 100644
--- a/lib/PhpParser/Lexer/Emulative.php
+++ b/lib/PhpParser/Lexer/Emulative.php
@@ -11,6 +11,8 @@ class Emulative extends \PhpParser\Lexer
 {
     protected $newKeywords;
     protected $inObjectAccess;
+    protected $keywordsReservedContextAllowed;
+    protected $allowKeywordsReserved;
 
     const T_ELLIPSIS   = 1001;
     const T_POW        = 1002;
@@ -40,6 +42,11 @@ class Emulative extends \PhpParser\Lexer
             ),
         );
 
+        // GH-202
+        if (version_compare(PHP_VERSION, self::PHP_5_4, '<')) {
+            $this->allowKeywordsReserved = array(Parser::T_CLASS, Parser::T_FUNCTION);
+        }
+
         $this->newKeywords = array();
         foreach ($newKeywordsPerVersion as $version => $newKeywords) {
             if (version_compare(PHP_VERSION, $version, '>=')) {
@@ -66,6 +73,7 @@ class Emulative extends \PhpParser\Lexer
 
     public function startLexing($code) {
         $this->inObjectAccess = false;
+        $this->keywordsReservedContextAllowed = false;
 
         $preprocessedCode = $this->preprocessCode($code);
         parent::startLexing($preprocessedCode);
@@ -212,16 +220,20 @@ class Emulative extends \PhpParser\Lexer
     }
 
     public function getNextToken(&$value = null, &$startAttributes = null, &$endAttributes = null) {
+        //if ($this->pos < 0) error_log ( __FUNCTION__ . " tokens: \n" . print_r($this->tokens, true) );
         $token = parent::getNextToken($value, $startAttributes, $endAttributes);
+        //error_log ( __FUNCTION__ . " pos: " . $this->pos . ", next:\n" . print_r($token, true) . PHP_EOL . print_r($value, true));
 
         // replace new keywords by their respective tokens. This is not done
         // if we currently are in an object access (e.g. in $obj->namespace
         // "namespace" stays a T_STRING tokens and isn't converted to T_NAMESPACE)
         if (Parser::T_STRING === $token && !$this->inObjectAccess) {
-            if (isset($this->newKeywords[strtolower($value)])) {
+            if (isset($this->newKeywords[strtolower($value)]) && !$this->keywordsReservedContextAllowed) {
                 return $this->newKeywords[strtolower($value)];
             }
         } else {
+            $this->keywordsReservedContextAllowed = in_array($token, $this->allowKeywordsReserved);
+
             // keep track of whether we currently are in an object access (after ->)
             $this->inObjectAccess = Parser::T_OBJECT_OPERATOR === $token;
         }

```

**Comment by nikic** [comment] 2015-05-27 17:23
@llaville This will solve the issue for your particular code - if it's really *exactly* that code. However, if something declares a class `Trait`, chances are that it's also going to be used somewhere - like `new Trait` or `Trait::FOO`. To make this work for more than reduced example code, all possible occurrences of identifiers would have to be supported. From the research into this topic done for the php-src context sensitivity patch, this is not feasible.

**Comment by llaville** [comment] 2015-05-27 17:30
Of course I understand. On the concept we keep it going with something equivalent that do no check the current `$allowKeywordsReserved` configuration, but by setting only a `$allowKeywordsReserved  = true` and do not replaced new keywords when we run with PHP 5.3 (keep T_STRING). That will allow all contexts (as you explainded)
Hope I'm enough clear on my new comment !

**Comment by llaville** [comment] 2015-05-27 17:40
That will give something like 

```
diff --git a/lib/PhpParser/Lexer/Emulative.php b/lib/PhpParser/Lexer/Emulative.php
index 837def4..5e79b54 100644
--- a/lib/PhpParser/Lexer/Emulative.php
+++ b/lib/PhpParser/Lexer/Emulative.php
@@ -11,6 +11,7 @@ class Emulative extends \PhpParser\Lexer
 {
     protected $newKeywords;
     protected $inObjectAccess;
+    protected $allowKeywordsReserved;
 
     const T_ELLIPSIS   = 1001;
     const T_POW        = 1002;
@@ -40,6 +41,9 @@ class Emulative extends \PhpParser\Lexer
             ),
         );
 
+        // GH-202
+        $this->allowKeywordsReserved = version_compare(PHP_VERSION, self::PHP_5_4, '<');
+
         $this->newKeywords = array();
         foreach ($newKeywordsPerVersion as $version => $newKeywords) {
             if (version_compare(PHP_VERSION, $version, '>=')) {
@@ -66,6 +70,7 @@ class Emulative extends \PhpParser\Lexer
 
     public function startLexing($code) {
         $this->inObjectAccess = false;
+        $this->keywordsReservedContextAllowed = false;
 
         $preprocessedCode = $this->preprocessCode($code);
         parent::startLexing($preprocessedCode);
@@ -212,13 +217,15 @@ class Emulative extends \PhpParser\Lexer
     }
 
     public function getNextToken(&$value = null, &$startAttributes = null, &$endAttributes = null) {
+        //if ($this->pos < 0) error_log ( __FUNCTION__ . " tokens: \n" . print_r($this->tokens, true) );
         $token = parent::getNextToken($value, $startAttributes, $endAttributes);
+        //error_log ( __FUNCTION__ . " pos: " . $this->pos . ", next:\n" . print_r($token, true) . PHP_EOL . print_r($value, true));
 
         // replace new keywords by their respective tokens. This is not done
         // if we currently are in an object access (e.g. in $obj->namespace
         // "namespace" stays a T_STRING tokens and isn't converted to T_NAMESPACE)
         if (Parser::T_STRING === $token && !$this->inObjectAccess) {
-            if (isset($this->newKeywords[strtolower($value)])) {
+            if (isset($this->newKeywords[strtolower($value)]) && !$this->allowKeywordsReserved) {
                 return $this->newKeywords[strtolower($value)];
             }
         } else {
```

Keep keywords as T_STRING, do not replaced it by `$newKeywords` token values only if we run PHP 5.3

**Comment by llaville** [comment] 2015-05-27 17:44
In my PHP test script (previously defined at top) replaced the `$code` with such sample 

````php
<?php

$code = '<?php

class Trait
{
    const FOO = "foo";
}

class finally
{
    function __construct()
    {
        $trait = new Trait;
        
        $foo = Trait::FOO;
    }
}
';
```
It seems good

**Comment by llaville** [comment] 2015-05-28 09:44
A concrete example and basic implementation, if you want to solve this issue, is presented (will lot of explains) in https://github.com/llaville/php-compat-info/issues/202#issuecomment-106249945

**Comment by llaville** [comment] 2015-06-04 11:55
@nikic You'll be perharps interrested by solution (update) I found and implemented in https://github.com/llaville/php-compat-info/issues/202#issuecomment-108857062

In summary, here are modifications on my Emulative Lexer version
https://github.com/llaville/php-reflect/commit/c8281072da0980c5e7b7bdfb72cc354d93e8144c

**Comment by llaville** [comment] 2015-06-29 16:29
@nikic Almost one month I used my copy of modified Emulative lexer (see previous comment, commit in php-reflect project) in real condition without found a new issue.

Did you think we could integrate it in PHP-Parser ? If not, close this issue at your disposal, I'll keep a copy in my project !

**Comment by nikic** [comment] 2015-06-29 20:37
@llaville Just took a look at your code and I don't think this solution is stable enough for general use. For example this pretty "normal" code will not work, unless I missed something:

```php
if (!trait_exists('Foo')) {
    trait Foo { ... }
}
```

**Comment by llaville** [comment] 2015-06-30 07:07
@nikic You right, and I fixed this issue with commit https://github.com/llaville/php-reflect/commit/4be20c38f8b11ada5b1ef7ddf549581c7ecd060a
Thanks

**Comment by nikic** [comment] 2015-07-02 16:13
@llaville It fixes this particular issue, but the problem is more general. Especially `yield` can occur practically everywhere, e.g. you can write `5 * yield`.

**Comment by nikic** [comment] 2015-08-25 17:12
Closing this, as I don't plan to support it.

**Closed by nikic** 2015-08-25 17:12 UTC
