### ISSUE TITLE
Creating new method call with old variable node adds undesired spaces

### ISSUE THREAD

**Issue by TomasVotruba** [nikic/PHP-Parser#466] opened 2018-01-14 00:30 UTC
I have tried many paths myself but I could not find a way to fix this.

We're working on Rector, that would split fluent calls to stadnalone methods:

```diff
-        $this->someClass->someFunction()->otherFunction();
+        $this->someClass->someFunction();
+        $this->someClass->otherFunction();
```

First line indent works well, thanks to:

```php
$node->setAttribute(Attribute::ORIGINAL_NODE, null);
```

But the second line - new `Expression` - does fail:

```diff
         $this->someClass->someFunction();
-        $this->someClass->otherFunction();
+                        $this->someClass->otherFunction();
```

This is the responsible method: https://github.com/rectorphp/rector/pull/286/files#diff-898aab094a6fedc75dd990d39c8a8f04R77

What should I do to fix this? Thank you

**Comment by nikic** [comment] 2018-01-16 12:25
Test case

```
<?php
$this->foo = new Foo;
$this->foo->a()
          ->b();
-----
$outerCall = $stmts[1]->expr;
$innerCall = $outerCall->var;
$var = $innerCall->var;
$stmts[1]->expr = $innerCall;
$stmts[2] = new Stmt\Expression(new Expr\MethodCall($var, $outerCall->name));
-----
<?php
$this->foo = new Foo;
$this->foo->a();
$this->foo->b();
```

**Comment by TomasVotruba** [comment] 2018-01-17 08:37
I simplifed the code, thanks for tips. But still the space remains.

I can't change nodes with manual `stmts[1]` access, since I use `NodeVisitor`

I think issues might be related to adding of nodes in `leaveNode()` method.
It calls this visitor: 

https://github.com/rectorphp/rector/blob/4cb74969d594f60aefc2c0ab1876593849debae8/src/NodeVisitor/ExpressionAddingNodeVisitor.php#L30

**Comment by TomasVotruba** [comment] 2018-01-17 08:41
Intereseting! When I return this:

```php
# leaveNode() method
       return [
            $node,
            new Node\Stmt\Expression(new String_('one')),
            new Node\Stmt\Expression(new String_('two'))
        ];
```

It will return:

```diff
-        $this->someClass->otherFunction();\n
+                        'one';\n
+                        'two';\n
```

---

When I return this:

```php
        $node->setAttribute(Attribute::ORIGINAL_NODE, null);

        return [
            $node,
            new Node\Stmt\Expression(new String_('one')),
            new Node\Stmt\Expression(new String_('two'))
        ];
```

It will return

```diff
-        $this->someClass->otherFunction();\n
+                        $this->someClass->someFunction();\n
+                        'one';\n
+                        'two';\n

```

**Comment by TomasVotruba** [comment] 2018-01-17 08:51
**It looks like it respect indent of outer call**

```php
        $this->someClass->someFunction()
        ->otherFunction();
```

```diff
-        $this->someClass->someFunction()
+        $this->someClass->someFunction();
+        $this->someClass ->otherFunction();
```

and 

```php
        $this->someClass->someFunction()
            ->otherFunction();
```
```diff
-        $this->someClass->someFunction()
+        $this->someClass->someFunction();
    +        $this->someClass ->otherFunction();
```

**Comment by nikic** [comment] 2018-01-17 11:28
Sorry for the confusion, this was just a reduced reproduce case for my test suite. It's a PHP-Parser bug, not in your code. The issue is that the indentation of the insertion point is taken, while what we really want something like the indentation of the previous element.

**Comment by TomasVotruba** [comment] 2018-01-21 10:29
I see. Thanks do update. So there is nothing I can do right now?

**Comment by nikic** [comment] 2018-01-25 21:10
Should be fixed now. Can you please check that this works and doesn't break indentation in other cases?

**Closed** 2018-01-25 21:09 UTC

**Comment by TomasVotruba** [comment] 2018-01-26 09:23
Works like a charm, thanks! :bowing_man:
